67 implement smartcar frontcam
DIT113-V22/group-02 pull request #78
Opened 2022-05-09 14:27 UTC by adityak714

For now, the app is able to show a front camera livestream with decent speed, and color-matched to the mod. Upcoming plan for later during the sprint:

- Setup cam#2 with birdseye view in #64. Need to add an extra camera (change in vehicle_config.json)

**NOTE: All team members need SMCE to be updated to a later version to handle multiple camera implementation further on.**

- The 2 buttons that were added in Android are to be implemented more in depth during the first half of sprint3, where they will be mapped to show the broadcast in the camera view based on which button is clicked (change MainActivity.java and activity_main.xml)
- Shift the location of the front camera up vertically, up to the level of the dashboard, and potentially back so that a more realistic POV-angle can be seen in the app (change in godot mod)

### :ballot_box_with_check: Definition of Done checklist
- [x] Meaningful title and valuable description in pull request
- [x] Code change tested manually if not covered by automated tests
- [x] Pull request linked to one or more issues/stories
- [ ] Acceptance criteria of the linked stories satisfied
- [x] Code change comprehended by those who approved it
- [x] State of target branch maintained or improved after the code change

2022-05-18 14:16 UTC, adityak714 commented
> I suggest taking a look at what your friends are doing at [DIT113-V22/group-08#63](https://github.com/DIT113-V22/group-08/pull/63) ;) uploading the .pck will very much slowdown the git repo over time

@RuthgerD Ok ... I went through their pull request, but I don't understand this line here:

DIT113-V22/group-08#63
```image: barichello/godot-ci:mono-latest```

2022-05-18 14:41 UTC, adityak714 commented
> This means it uses that docker image for the ci run instead of the default ubuntu one; in short it provides the godot binary.
> 
> I suggest making a separate issue for this if you want to try implementing it

Alright got it, thanks for the suggestion king 👑

2022-05-18 15:15 UTC, sh4r10 requested changes
The buttons for the camera views should be removed from this branch, not only do they take up too much space they are also unnecessary for the issue itself. A button will be later on which takes care of switching between the two cameras, but as of now, this is not needed.

2022-05-21 11:33 UTC, um33 commented
looks fine to me because  i did some work on this branch with Aditya so everything is understandable to me.

2022-05-21 11:44 UTC, Gabri1998 commented
The Car-FrontCamera almost fixed except that we need to do some identification in the code  between the FrontCamera and the Birdseye view camera . other than that It works as it supposed to be

2022-05-21 13:31 UTC, adityak714 commented
> The buttons for the camera views should be removed from this branch, not only do they take up too much space they are also unnecessary for the issue itself. A button will be later on which takes care of switching between the two cameras, but as of now, this is not needed.

Commit 88fb92e should fix this. @um33 and me removed the buttons here.

2022-05-23 06:51 UTC, arrestoteles commented
@adityak714 @um33 "P" button doesn't work - is it supposed to be implemented in this branch? Good work with the frontcam! 📸

2022-05-23 07:07 UTC, arrestoteles commented on arduino/smartcar/smartcar.ino
> +const auto oneSecond = 1000UL;
Constants should be capitalized no?

2022-05-23 07:20 UTC, um33 commented
> @adityak714 @um33 "P" button doesn't work - is it supposed to be implemented in this branch? Good work with the frontcam! 📸
> 
> Also, we should change the acceptance criteria for issue #67

P button just not working on this branch but it is working on the master.

2022-05-23 07:23 UTC, um33 commented
now camera is not working on my branch after updating the SMCE new version, happened with one other group mate as well @RuthgerD

2022-05-23 07:36 UTC, RuthgerD commented
If you're using a custom config for it you need to update some keys as the way it works changed :) check the slack announcement thread for info

2022-05-24 15:23 UTC, um33 approved these changes, later dismissed
This is good, I have tested it on my Android emulator and the cam feed is working as normal now. Also tested on another computer's emulator, and in method calls for autopark and retrieve(), cam feed does not stop anymore. New setup for board_config and vehicle_config, so all in team need to update smce 1.3.4 and birdseye cam can be started, if time allows

2022-05-24 15:56 UTC, sh4r10 approved these changes
The branch covers the acceptance criteria of the related issue, the changes have been testing manually and no problems were encoutered. This is ready to be merged.

2022-05-24 15:59 UTC, merged